language: ruby
os: linux

services:
  - redis-server
rvm:
  - 2.7.1
  - ruby-head
  - truffleruby
before_install:
  - gem update --system
  - gem install bundler
script: bundle exec rspec
jobs:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: truffleruby
