language: ruby
os: linux

services:
  - redis
rvm:
  - 2.7.2
  - 3.0.0
  - ruby-head
  - truffleruby
before_install:
  - gem update --system
  - gem install bundler
script: bundle exec rspec
jobs:
  fast_finish: true
  allow_failures:
    - rvm: 3.0.0
    - rvm: ruby-head
    - rvm: truffleruby
